### ISSUE TITLE
Dialog issue

### ISSUE THREAD

**Issue by simonatocanie** [sdl/Multiselect-ComboBox#27]
Hi,

I'm not sure if is an issue here or I'm doing something wrong. I have a window which opens another window when i press  button Test. This new window have a Multiselect-ComboBox, but when i open this window there are no items in the Multiselect-ComboBox. 
I made a test on a test project because i don't know what the issue. The initial window:
![image](https://user-images.githubusercontent.com/43148857/66200171-210ef280-e6a9-11e9-86ef-b51d60f293be.png)

From the second window(the same), I don't have any items.
![image](https://user-images.githubusercontent.com/43148857/66200228-3c79fd80-e6a9-11e9-8309-c2e480f241a8.png)

I mention that I want to use it with dialoghost from materialDesign but because i didn't have any idea where is the issue,  i test it with ShowDialog.

Thank you,
Simona

**Comment by cromica** [comment]
Hi @simonatocanie ,

Would it be possible to send a sample project?

**Comment by Impertatore** [comment]
Hi @simonatocanie, I responded to a similar issue a while back, as follows:
https://github.com/sdl/Multiselect-ComboBox/issues/5

not sure if that helps?

**Comment by simonatocanie** [comment]
Hi,
Thank you very much for your help.  I didn't had access on my laptop until now. It's working now.

You can close the issue.

Have a nice evening!

**Comment by cromica** [comment]
Not an actual issue.
