### ISSUE TITLE
Port to .Net Core 3.0

### ISSUE THREAD

**Issue by danielklecha** [sdl/Multiselect-ComboBox#36]
Hi!
Is there a chance that You will move this library to next level and port it to .Net Core 3?
Best
Daniel

**Comment by Mrxx99** [comment]
I made a pull request for dual targeting .net framework and .net core 3.1 (#42)

**Comment by sekulicb** [comment]
Still not supported. What's the hold up ?

**Comment by wyrdfish** [comment]
.net 3.1 is supported.
