### ISSUE TITLE
"SelectedItems" always equals null

### ISSUE THREAD

**Issue by Vya4ik003** [sdl/Multiselect-ComboBox#38]
Hello!
As the name suggests, field of object of class  "MultiSelectComboBox" such as "SelectedItems" always equals null. 
My application include 3 buttons "Show all selected items", "Show first selected item" and "Show last selected item", and one MultiSelectComboBox.
When i picked few items, in "MultiSelectComboBox_SelectedItemsChanged" i wrote `MessageBox.Show(multiSelectComboBox.SelectedItems.ToString());`, and after next selection of item i get error : "SelectedItems" returned null .
Thank you in advance!

**Comment by abx78** [comment]
It works correctly here. How did you attach the event to the Grid?
I did a simple 

`<sdl:MultiSelectComboBox Name="XXX"
    SelectedItemsChanged="OnSelectedItemsChanged" />`

Code behind:
`private void OnSelectedItemsChanged(object sender, SelectedItemsChangedEventArgs e)
{
    MessageBox.Show(XXX.SelectedItems.ToString());
}`

It seems to work fine.

**Comment by Impertatore** [comment]
Hi @Vya4ik003 
You should subscribe to event behaviour **SelectedItemsChangedBehaviour.SelectedItemsChanged** that allows you to bind that event to an ICommand in your view model, to identify when something changes.

Please make reference to the documentation or example project for reference:

**Example:**
sdl:SelectedItemsChangedBehaviour.SelectedItemsChanged="{Binding SelectedItemsChangedCommand}"
