### ISSUE TITLE
Multiselect-ComboBox in a modal dialog

### ISSUE THREAD

**Issue by p0ria** [sdl/Multiselect-ComboBox#5]
Hi, Thanks for your useful control.
This control does not work in a modal dialog.
The ItemsSource property is always empty.

**Comment by Impertatore** [comment]
Hi @p0ria, can you please provide an example so I can understand better what problem you are facing with setting the ItemSource binding?  send to phartnett@sdl.com

**Comment by p0ria** [comment]
Here is my sample:
public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }

        private void ButtonShowModalWindow_OnClick(object sender, RoutedEventArgs e)
        {
            var dlg = new ModalWindow();
            dlg.DataContext = new ModalWindow();;
            dlg.Show();
        }
    }

    public class ModalWindowVM : INotifyPropertyChanged
    {
        private ObservableCollection<Person> people;

        public ModalWindowVM()
        {
            People = new ObservableCollection<Person>
            {
                new Person{Id = 1, Name = "Pooria"},
                new Person{Id = 2, Name = "Ahmad"}
            };
        }

        public ObservableCollection<Person> People
        {
            get { return people; }
            set
            {
                people = value;
                OnPropertyChanged();
            }
        }

        private List<Person> _selectedPeople = new List<Person>();

        public IEnumerable<Person> SelectedPeople
        {
            get { return _selectedPeople; }
            set
            {
                _selectedPeople = new List<Person>(value);
            }
        }

        public event PropertyChangedEventHandler PropertyChanged;

        [NotifyPropertyChangedInvocator]
        protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }

    public class Person
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }

<Window x:Class="ModalWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WpfApp6"
        xmlns:sdl="http://schemas.sdl.com/xaml"
        mc:Ignorable="d"
        Title="PopupWindow" Height="450" Width="800">
    <Window.Resources>
        <DataTemplate x:Key="MultiSelectComboBoxDropDownItemTemplate" DataType="local:Person">
            <Grid>
                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="50" />
                    <ColumnDefinition Width="*" />
                </Grid.ColumnDefinitions>

                <TextBlock Text="{Binding Path=Id}" />
                <TextBlock Grid.Column="1" Text="{Binding Path=Name}" Margin="5 0 0 0" />
            </Grid>
        </DataTemplate>
        <DataTemplate x:Key="MultiSelectComboBoxSelectedItemTemplate" DataType="local:Person">
            <TextBlock Text="{Binding Path=Name}" Margin="2,0" />
        </DataTemplate>
    </Window.Resources>
    <StackPanel x:Name="Panel">
        <sdl:MultiSelectComboBox x:Name="cmbox"
                                 Margin="3"
                                 Height="50"
                                 DropdownItemTemplate="{StaticResource MultiSelectComboBoxDropDownItemTemplate}"
                                 SelectedItemTemplate="{StaticResource MultiSelectComboBoxSelectedItemTemplate}"
                                 IsEditable="True"
                                 SelectedItems="{Binding SelectedPeople}"
                                 ItemsSource="{Binding Path=People, Mode=OneWay}" />
        <Button  Click="ButtonBase_OnClick">Press</Button>
    </StackPanel>
</Window>

**Comment by p0ria** [comment]
**And here is my Modal Window xaml file**

```
<Window x:Class="ModalWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WpfApp6"
        xmlns:sdl="http://schemas.sdl.com/xaml"
        mc:Ignorable="d"
        Title="PopupWindow" Height="450" Width="800">
    <Window.Resources>
        <DataTemplate x:Key="MultiSelectComboBoxDropDownItemTemplate" DataType="local:Person">
            <Grid>
                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="50" />
                    <ColumnDefinition Width="*" />
                </Grid.ColumnDefinitions>

                <TextBlock Text="{Binding Path=Id}" />
                <TextBlock Grid.Column="1" Text="{Binding Path=Name}" Margin="5 0 0 0" />
            </Grid>
        </DataTemplate>
        <DataTemplate x:Key="MultiSelectComboBoxSelectedItemTemplate" DataType="local:Person">
            <TextBlock Text="{Binding Path=Name}" Margin="2,0" />
        </DataTemplate>
    </Window.Resources>
    <StackPanel x:Name="Panel">
        <sdl:MultiSelectComboBox x:Name="cmbox"
                                 Margin="3"
                                 Height="50"
                                 DropdownItemTemplate="{StaticResource MultiSelectComboBoxDropDownItemTemplate}"
                                 SelectedItemTemplate="{StaticResource MultiSelectComboBoxSelectedItemTemplate}"
                                 IsEditable="True"
                                 SelectedItems="{Binding SelectedPeople}"
                                 ItemsSource="{Binding Path=People, Mode=OneWay}" />
        <Button  Click="ButtonBase_OnClick">Press</Button>
    </StackPanel>
</Window>
```

**Comment by p0ria** [comment]
> I create an instance of ModalWindow class, set its DataContext property and Show() it.
> But when the ModalWindow opens, the inner MultiSelectComboBox is empty...
> I tested it in MainWindow (MultiSelectComboBox inside MainWindow instead of ModalWindow) and it worked, but it does not work inside ModalWindow.

**Comment by Impertatore** [comment]
Hi @p0ria, please make the following changes and confirm again:

1. dlg.DataContext = new ModalWindowVM();

2. public ObservableCollection<Person> People
      {
          get { return people; }
          set
          {
              people = value;
              OnPropertyChanged(nameof(People));
          }
      }

**Comment by p0ria** [comment]
I did it does not work yet.
Can you please test it?

**Comment by Impertatore** [comment]
Hi @p0ria, yes I have tested and did not see any problems.

I have uploaded a simple example project, taking into consideration your example code above.  The project is located [here](https://www.dropbox.com/s/11d9loed6upaad0/MultiComboBoxDemo101.zip?dl=0).

It demonstrates loading the view (as a model window) after setting the data context without any issues.  Please download the project, review it and confirm that you can run/debug it on your computer + that it represents a working solution of the issue that you are describing. 

If for some reason the project that I have provided you does not represent what you are describing, then I would ask you to please send me the solution (or an extract of it) that you working on so that I can have more context to reproducing.

Example:



Startup: Startup.cs
`public class Startup
	{		
		public void Execute()
		{
			// Instantiate window
			var view = new View.ExampleView();

			// Instantiate model
			var model = new ExampleViewModel();

			// assign the data context
			view.DataContext = model;

			// show window modally
			view.ShowDialog();
		}
	}`

Model: Person
`public class Person: INotifyPropertyChanged
	{
		public int Id { get; set; }
		public string Name { get; set; }

		public override string ToString()
		{
			return Name;
		}

		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
		{
			PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
		}
	}`

ViewModel: ExampleViewModel.cs
`public class ExampleViewModel: INotifyPropertyChanged
	{		
		private ObservableCollection<Person> _people;
		private List<Person> _selectedPeople;

		public ExampleViewModel()
		{
			People = new ObservableCollection<Person>
			{
				new Person{Id = 1, Name = "Pooria"},
				new Person{Id = 2, Name = "Ahmad"}
			};
		}

		public ObservableCollection<Person> People
		{
			get => _people;
			set
			{
				_people = value;
				OnPropertyChanged(nameof(People));
			}
		}

		public List<Person> SelectedPeople
		{
			get => _selectedPeople ?? (_selectedPeople = new List<Person>());
			set
			{
				_selectedPeople = value;
				OnPropertyChanged(nameof(SelectedPeople));
			}
		}

		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
		{
			PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
		}
	}`

View: ExampleView.xaml
`<Window x:Class="MultiComboBoxDemo101.View.ExampleView"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:MultiComboBoxDemo101"
        xmlns:sdl="http://schemas.sdl.com/xaml"
        xmlns:viewModel="clr-namespace:MultiComboBoxDemo101.ViewModel"
        xmlns:model="clr-namespace:MultiComboBoxDemo101.Model"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800" d:DataContext="{d:DesignInstance viewModel:ExampleViewModel}">

	<Window.Resources>
		<DataTemplate x:Key="MultiSelectComboBoxDropDownItemTemplate" DataType="model:Person">
			<Grid>
				<Grid.ColumnDefinitions>
					<ColumnDefinition Width="50" />
					<ColumnDefinition Width="*" />
				</Grid.ColumnDefinitions>

				<TextBlock Text="{Binding Path=Id}" />
				<TextBlock Grid.Column="1" Text="{Binding Path=Name}" Margin="5 0 0 0" />
			</Grid>
		</DataTemplate>
		<DataTemplate x:Key="MultiSelectComboBoxSelectedItemTemplate" DataType="model:Person">
			<TextBlock Text="{Binding Path=Name}" Margin="2,0" />
		</DataTemplate>
	</Window.Resources>

	<Grid>
		<StackPanel x:Name="Panel" Margin="10">
			<sdl:MultiSelectComboBox Margin="10"  Height="50" IsEditable="True"
			                         DropdownItemTemplate="{StaticResource MultiSelectComboBoxDropDownItemTemplate}"
			                         SelectedItemTemplate="{StaticResource MultiSelectComboBoxSelectedItemTemplate}"			                         	
			                         SelectedItems="{Binding SelectedPeople}"
			                         ItemsSource="{Binding Path=People, Mode=OneWay}" />
			<Button Margin="10">Press</Button>
		</StackPanel>
	</Grid>
</Window>`

**Comment by p0ria** [comment]
hi @Impertatore, yes your sample works, but my problem is when the a window makes a modal window.
I mean this one:
        ```
public partial class ExampleView : Window
	{
		public ExampleView()
		{
			InitializeComponent();
		}

	    private void ButtonPress_OnClick(object sender, RoutedEventArgs e)
	    {
	        // Instantiate window
	        var view2 = new View.ExampleView();

	        // Instantiate model
	        var model = new ExampleViewModel();

	        // assign the data context
	        view2.DataContext = model;

	        // show window modally
	        view2.ShowDialog();
        
        }
	}
```

I also uploaded my solution [here](https://www.dropbox.com/s/8ne7ast1bmgfkvl/MultiComboBoxDemo101.rar?dl=0). When you click on _press_ button, the MultiselectComboBox in side the **new Modal Window** is not populated.

**Comment by Impertatore** [comment]
Hi @p0ria,
Thank you for providing more context with the example code.
It is not possible to achieve the result that you are expecting in this case, as the data tree doesn't exist yet.  In this case you should assign the data context after the view has loaded.

I have included a working example here:
[MultiComboBoxDemo102.zip](https://github.com/sdl/Multiselect-ComboBox/files/3185853/MultiComboBoxDemo102.zip)


**example**:
`public partial class SettingsView : Window
{
	private readonly SettingsViewModel _model;

	public SettingsView(SettingsViewModel model)
	{
		_model = model;

		InitializeComponent();

		Loaded += SettingsView_Loaded;
	}

	private void SettingsView_Loaded(object sender, RoutedEventArgs e)
	{
		Loaded -= SettingsView_Loaded;

		DataContext = _model;
	}
}`

**Comment by p0ria** [comment]
Hi @Impertatore. Yes It works this way. 
Thank you so much for your patient and answer.
