### ISSUE TITLE
SelectedItems property

### ISSUE THREAD

**Issue by p0ria** [sdl/Multiselect-ComboBox#6]
Hi
How can I have SelectedItems in my ViewModel.
I bind the SelectedItems to a property in my viewmodel, but the setter never gets called.
I also tried this one:
```
<i:Interaction.Triggers>
        <i:EventTrigger EventName="SelectedItemsChanged">
            <i:InvokeCommandAction Command="{Binding Path=SelectedItemsChangeCommand"} CommandParameter="{Binding ElementName=multiSelectComboBox, Path=SelectedItems}"/>
        </i:EventTrigger>
</i:Interaction.Triggers>
```
but the argument to my command is always same.
thanks in advance for your help.

**Comment by Impertatore** [comment]
We have introduced two event behaviors to accommodate binding events to a command when the **Filter Text** and **Selected Items** change.  I have included an example of how to subscribe to these from the documentation and working example.
Basically, you include a command in the view model and then bind the event to it.

**example:**
<sdl:MultiSelectComboBox Height="100"
                ItemsSource="{Binding Items}"               
                sdl:SelectedItemsChangedBehaviour.SelectedItemsChanged="{Binding SelectedItemsChangedCommand}"/>
