### ISSUE TITLE
Multiselect-Combobox do not work on IE 11

### ISSUE THREAD

**Issue by domiq44** [sdl/Multiselect-ComboBox#7]
Hello,

Great work !
I have to use such a component both with Chrome and IE.
When I play with [demo](https://multiselect-combo-box.firebaseapp.com/demo/), I See that it does'nt work on it !
Is there any turn arround ?

Thanks.

Dominique

**Comment by Impertatore** [comment]
Hi @domiq44,
The JavaScript demo that you are making reference to is not connected with this project. SDL/Multiselect-Combobox is a WPF custom control

**Comment by domiq44** [comment]
Oh sorry !
