### ISSUE TITLE
load on demand

### ISSUE THREAD

**Issue by danielklecha** [sdl/Multiselect-ComboBox#8]
First of all - control looks great!

I am wondering if you have plans to build on demand feature in this project.
I know thiat is complicated thing.

I worry that will be problem when I attach collection with 1 million records.
Do you have experience how it will work with your control?

Something similar is available in [wpf.lazycombobox](https://github.com/utillity/wpf.lazycombobox) but it's the only feature of this control...

IItemGroup interface will complicate on-demand feature but control can pass to "SourceService" additional information with last group and read next package with items.

Best

**Comment by cromica** [comment]
Thank you @danielklecha. At the moment we have no plans for implementing lazy loading. We do accept any contributions though.

**Comment by danielklecha** [comment]
@cromica I implemented lazy loading for your control in #10. It's similar to wpf.lazycombobox solution.
I hope that you or other contributor) can verify it and approve or give some tips.
Thanks!

**Comment by safi-07** [comment]
@cromica any updates on this. I think this feature added by @danielklecha  should be included.

**Comment by safi-07** [comment]
@danielklecha I think the name should be ISuggestionProvider or and Dependency Property Should be named as SuggestionProvider. GetMissingItemsAsync should be replace by GetSuggestions.

**Comment by danielklecha** [comment]
@safi-07 I updated the names.
@cromica I did some additional tests with my own project and I didn't find any issues with this feature.

**Comment by safi-07** [comment]
@danielklecha. I think there is a problem with usability of this box when we select single item mode. It shoule be more like attached image control of jquery [select2](https://select2.org/getting-started/basic-usage). Right now it seems like we are selecting another item. When we are not. Do you think its worth working on?. I think we should make search box a separate TemplatePart. Currently I am trying to make this happen on your code. Should I do it?
![Select 2](https://user-images.githubusercontent.com/16310125/66481420-53aa5800-eaba-11e9-927c-da68deb51c1f.PNG)

**Comment by danielklecha** [comment]
@safi-07 I think that your idea is better than current solution. If you want to change my code then I don't have contraindications.

**Comment by danielklecha** [comment]
@safi-07 I though about it second time.
I worry that behavior of the control will be inconsicted for the user after change.
If you move "search box" to dropdown then for single mode... if you switch between controls then you won't be able to search - unless you expand dropdown and change focus.
So maybe it wil generate more problems than advantages...
But maybe I misunderstand something in this concept.

I found two different problems in demo:
- when you click inside combo, click tab then focus will be moved to "clear selected items" (PASS), but when you click shift+tab and back to combobox then focus is on "search box" but you can't wrote anything (FAIL)
- when you choose single mode and click "select 20 random items" ten you will see 20 items in combobox (FAIL). But we don't have access to collection change event in IList in library so it could be fixed just in example.

**Comment by safi-07** [comment]
@danielklecha why are you calling  `LoadSuggestions(string.Empty);` in `CloseDropdownMenu(bool clearFilter, bool moveFocus)` ?

**Comment by danielklecha** [comment]
@safi-07 This method has different name previously. I didn't added this call. It was there before my changes.

**Comment by safi-07** [comment]
@danielklecha  I have fixed Tab Navigations and Scrolling issues. I have also added some new useful features. Please pull my latest code

**Comment by safi-07** [comment]
@danielklecha Please take a look at your async method. I dont think you have implemented it the right way. Async Method should be Suffix with async. They should be async all the way. 

[https://medium.com/@deep_blue_day/long-story-short-async-await-best-practices-in-net-1f39d7d84050](Best Practices Async and Await Article)

[https://www.youtube.com/watch?v=My2gAv5Vrkk](Async Await Best Practices Video)

**Comment by safi-07** [comment]
@danielklecha  IsLoading feature that was introduced not working because Task.Run is not awaited. Please have a look. As per my understanding Task.Run is only used when I/O Bound Task are performed.

[https://blog.stephencleary.com/2013/11/taskrun-etiquette-examples-using.html](Task.Run Article)
[https://www.pluralsight.com/guides/using-task-run-async-await](Task.Run Article)

**Comment by danielklecha** [comment]
@safi-07 Are you thinking about code inside "LoadSuggestions" method?
Well... My idea was to run async task and leave current thread. And all changes on the end of this task put into function which we send to Tak.Run.  Also, we can add "Task.Run(...).ConfigureAwait(false)"
Otherwise we need to call Task.Run(...).Wait() but it will break whole concept.

Do you think that we should remove async code and replace it with sync methods? First version of my changes contains sync methods but I thought that is wrong and changed it...

[Simplest way to do a fire and forget method in c# 4.0](https://stackoverflow.com/questions/5613951/simplest-way-to-do-a-fire-and-forget-method-in-c-sharp-4-0)

I need to read more about async but I want to know what is wrong from your point.
I remember that "async" suffix should be added.

**Comment by safi-07** [comment]
@danielklecha if you are going to fetch a few records from million of records you must show some kind of loading record message to user. For that I have already added IsLoadingSuggestions and LoadingSuggestionsContent as dependency property. But as you are doing fire and forget this cant be executed. 

` IsLoadingSuggestions = true;
            Task.Run(async () =>
            {
                var items = await suggestionProvider.GetSuggestions(criteria, _suggestionProviderToken.Token);
                await Dispatcher.BeginInvoke(new Action(() =>
                {
                    if (suggestionProviderToken.IsCancellationRequested)
                    {
                        IsLoadingSuggestions = false;
                        return;
                    }
                    ItemsSource.Clear();
                    foreach (var item in items)
                        ItemsSource.Add(item);
                    if (!suggestionProviderToken.IsCancellationRequested)
                        ApplyItemsFilter(criteria);
                }));
            });
            IsLoadingSuggestions = false;`

**Comment by safi-07** [comment]
@danielklecha you don't need to use wait or make sync methods. Make methods async and use await with it.

**Comment by danielklecha** [comment]
@safi-07 I've moved async code to separate method
I added IsLoadingSuggestions property as comment - you need to uncomment it.
You should be able to this in LoadSuggestions method:
```c#
if (SuggestionProvider == null)
{
    ApplyItemsFilter(criteria);
    return;
}
IsLoadingSuggestions = true;
LoadSuggestionsAsync(criteria).ContinueWith(t => IsLoadingSuggestions = false, TaskContinuationOptions.ExecuteSynchronously);
```

**Comment by danielklecha** [comment]
@safi-07 As I wrote on github Dispatcher.BeginInvoke should work.

I think that this check should be added to ItemsSourceProperty, SelectedItemsProperty and SuggestionProviderProperty.
I had this problem in #26 - Property is updated before control is loaded.
I found workaround but dispatcher will be a better solution.
I can update the code if you want.

**Comment by safi-07** [comment]
Please do so if possible.

On Oct 17, 2019 10:19 PM, Daniel Klecha <notifications@github.com> wrote:

@safi-07<https://github.com/safi-07> As I wrote on github Dispatcher.BeginInvoke should work.

I think that this check should be added to ItemsSourceProperty, SelectedItemsProperty and SuggestionProviderProperty.
I had this problem in #26<https://github.com/sdl/Multiselect-ComboBox/issues/26> - Property is updated before control is loaded.
I found workaround but dispatcher will be a better solution.
I can update the code if you want.

**Comment by danielklecha** [comment]
@safi-07 I updated the code. I checked code again and it looks that we need to secure ItemsSourceProperty and SuggestionProviderProperty.
I created control using code behind and everything goes well. Please try it yourself.

**Comment by safi-07** [comment]
Thanks. Working.

**Comment by safi-07** [comment]
@danielklecha All Suggestions Provider are giving validation by default. Can you please either include Validation (Data Annotation Or Custom Validation. e.g Required Validation) or accept my Pull Request so that I can do it?.

**Comment by danielklecha** [comment]
I'm not sure about which part of the code you wrote but sure - I will
accept your pull request. Honestly, I've just seen it and there is few
conflicts so I need to have a moment. I will try to do that tomorrow.

niedz., 20.10.2019, 21:02 użytkownik safi-07 <notifications@github.com>
napisał:

**Comment by danielklecha** [comment]
I saw that my branch was merged to main so I close this issue.
